---
type: "auv_nn_speed_torch"
trainedFile: "/home/pierre/workspace/uuv_ws/src/mppi_ros/scripts/mppi_tf/torch-training/bluerov2/2022.08.28-19:48:51/nn-velocity_21x128x128x128x128x128x6.pb"
limMax: 1000.
limMin: 1000.
steps: 1
history: 1
rot: "rot"