---
    type: "static"
    diag: false
    goal:
      - 1.0
      - 0.0
      - 0.5
      - 0.0
    Q:
      - - 1.0
        - 0.0
        - 0.0
        - 0.0
      - - 0.0
        - 1.0
        - 0.0
        - 0.0
      - - 0.0
        - 0.0
        - 1.0
        - 0.0
      - - 0.0
        - 0.0
        - 0.0
        - 1.0
